// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Account struct {
	Id        int64     `json:"Id"`
	Balance   int64     `json:"Balance"`
	Owner     string    `json:"Owner"`
	Currency  string    `json:"Currency"`
	CreatedAt time.Time `json:"CreatedAt"`
}

type Entry struct {
	Id            int64     `json:"Id"`
	FromAccountId int64     `json:"FromAccountId"`
	Amount        int64     `json:"Amount"`
	CreatedAt     time.Time `json:"CreatedAt"`
}

type Transfer struct {
	Id            int64     `json:"Id"`
	FromAccountId int64     `json:"FromAccountId"`
	ToAccountId   int64     `json:"ToAccountId"`
	Amount        int64     `json:"Amount"`
	CreatedAt     time.Time `json:"CreatedAt"`
}

type User struct {
	Username          string    `json:"Username"`
	HashedPassword    string    `json:"HashedPassword"`
	FirstName         string    `json:"FirstName"`
	LastName          string    `json:"LastName"`
	Email             string    `json:"Email"`
	PasswordChangedAt time.Time `json:"PasswordChangedAt"`
	CreatedAt         time.Time `json:"CreatedAt"`
}
