// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transfert.sql

package db

import (
	"context"
)

const createTransfers = `-- name: CreateTransfers :one
INSERT INTO
    "transfer" (
        "FromAccountId",
        "ToAccountId",
        "BankName",
        "Amount"
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4
    ) RETURNING "Id", "FromAccountId", "BankName", "ToAccountId", "Amount", "CreatedAt"
`

type CreateTransfersParams struct {
	FromAccountId int64  `json:"FromAccountId"`
	ToAccountId   int64  `json:"ToAccountId"`
	BankName      string `json:"BankName"`
	Amount        int64  `json:"Amount"`
}

func (q *Queries) CreateTransfers(ctx context.Context, arg CreateTransfersParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfers,
		arg.FromAccountId,
		arg.ToAccountId,
		arg.BankName,
		arg.Amount,
	)
	var i Transfer
	err := row.Scan(
		&i.Id,
		&i.FromAccountId,
		&i.BankName,
		&i.ToAccountId,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransfers = `-- name: GetTransfers :one
SELECT
    "Id", "FromAccountId", "BankName", "ToAccountId", "Amount", "CreatedAt"
FROM
    "transfer"
WHERE
    "Id" = $1
LIMIT
    1
`

func (q *Queries) GetTransfers(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfers, id)
	var i Transfer
	err := row.Scan(
		&i.Id,
		&i.FromAccountId,
		&i.BankName,
		&i.ToAccountId,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT
    "Id", "FromAccountId", "BankName", "ToAccountId", "Amount", "CreatedAt"
FROM
    "transfer"
ORDER BY
    "Id" = $1 DESC
LIMIT
    1 OFFSET 2
`

func (q *Queries) ListTransfers(ctx context.Context, id int64) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.Id,
			&i.FromAccountId,
			&i.BankName,
			&i.ToAccountId,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
